export const candidates = [
  {
    name: "INESH HAQUE",
    image: "/candidates/president/Inesh.JPG",
    role: "president",
    poster: "",
    video: "",
  },
  {
    name: "HAMZA SALEH",
    image: "/candidates/president/Hamza.jpg",
    role: "president",
    poster: "/posters/president/hamza.pdf",
    video: "https://player.vimeo.com/video/1087609441?h=9e95efaa31&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
  {
    name: "DAVID CHEN",
    image: "/candidates/vicepresident/David.JPG",
    role: "vice president",
    poster: "/posters/vicepresident/david.pdf",
    video: "https://player.vimeo.com/video/1087607076?h=f787ec13a4&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
  {
    name: "ABDELRAHMAN ELSIDDIG",
    image: "/candidates/vicepresident/abdel.jpg",
    role: "vice president",
    poster: "/posters/vicepresident/abdel.pdf",
    video: "",
  },
  {
    name: "AMRITA RAJARAM",
    image: "/candidates/vicepresident/amrita.jpg",
    role: "vice president",
    poster: "/posters/vicepresident/amrita.pdf",
    video: "https://player.vimeo.com/video/1087614745?h=826f39bb46&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
  {
    name: "ISABELLE NG",
    image: "/candidates/socialconvenor/Isabelle.jpg",
    role: "social convenor",
    poster: "/posters/socialconvenor/isabelle.pdf",
    video: "https://player.vimeo.com/video/1087607126?h=445dde3d87&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
  {
    name: "NADINE MUGHAL",
    image: "/candidates/clubsliason/nadine.jpg",
    role: "clubs liason",
    poster: "/posters/clubsliason/nadine.pdf",
    video: "https://player.vimeo.com/video/1087607218?h=8125b69db4&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
  {
    name: "JHANVI PATEL",
    image: "/candidates/clubsliason/jhanvi.jpg",
    role: "clubs liason",
    poster: "/posters/clubsliason/jhanvi.pdf",
    video: "https://player.vimeo.com/video/1087607120?h=9558d6367d&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
  {
    name: "TIANNA LIM",
    image: "/candidates/socialconvenor/tianna.jpg",
    role: "social convenor",
    poster: "/posters/socialconvenor/tianna.pdf",
    video: "https://player.vimeo.com/video/1087607264?h=ff0d753bed&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
  },
    //   and more for social convenors, treasurers, and other roles
];