export const candidates = [
  {
    name: "INESH HAQUE",
    image: "/candidates/president/Inesh.JPG",
    role: "president",
    poster: "",
    video: "",
  },
  {
    name: "HAMZA SALEH",
    image: "/candidates/president/Hamza.jpg",
    role: "president",
    poster: "/posters/president/hamza.pdf",
    video: "",
  },
  {
    name: "DAVID CHEN",
    image: "/candidates/vicepresident/David.JPG",
    role: "vice president",
    poster: "/posters/vicepresident/david.pdf",
    video: "",
  },
  {
    name: "ABDELRAHMAN ELSIDDIG",
    image: "/candidates/vicepresident/abdel.jpg",
    role: "vice president",
    poster: "/posters/vicepresident/abdel.pdf",
    video: "",
  },
  {
    name: "AMRITA RAJARAM",
    image: "/candidates/vicepresident/amrita.jpg",
    role: "vice president",
    poster: "/posters/vicepresident/amrita.pdf",
    video: "",
  },
  {
    name: "ISABELLE NG",
    image: "/candidates/socialconvenor/Isabelle.jpg",
    role: "social convenor",
    poster: "/posters/socialconvenor/isabelle.pdf",
    video: "",
  },
  {
    name: "NADINE",
    image: "/candidates/clubsliason/nadine.jpg",
    role: "clubs liason",
    poster: "/posters/clubsliason/nadine.pdf",
    video: "",
  },
  {
    name: "JHANVI PATEL",
    image: "/candidates/clubsliason/jhanvi.jpg",
    role: "clubs liason",
    poster: "/posters/clubsliason/jhanvi.pdf",
    video: "",
  },
  {
    name: "TIANNA LIM",
    image: "/candidates/socialconvenor/tianna.jpg",
    role: "social convenor",
    poster: "/posters/socialconvenor/tianna.pdf",
    video: "",
  },
    //   and more for social convenors, treasurers, and other roles
];